version: 0.0
os: linux
files:
  - source: /aws
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: aws/scripts/after-install.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: aws/scripts/before-install.sh
      timeout: 300
      runas: root